INV_Lizenzen =
[
["car",university,localize "STRS_license_car",85],
["car",licensesBer,localize "STRS_license_car",85],
["car",mogilvekamayor,localize "STRS_license_car",85],
["car",TB,localize "STRS_license_car",85],
["air",TB,localize "STRS_license_air",350],
["air",licensesBer,localize "STRS_license_air",350],
["boat",university,localize "STRS_license_boat",100],
["truck",university,localize "STRS_license_truck",90],
["truck",licensesBer,localize "STRS_license_truck",90],
["diamond",Diamond_1,"Diamond processor's license",350],
["Baker",Bakery_1,"Baker's license",50],
["oil",Oil_1,"Oil processor's license",500],
["cocaine ga1",gangarea1,"GA1 cocaine Drug processor's license",2000],
["lsd ga1",gangarea1,"GA1 LSD Drug processor's license",2000],
["heroin ga2",gangarea2,"GA2 Heroin Drug processor's license",2000],
["lsd ga2",gangarea2,"GA2 LSD Drug processor's license",2000],
["heroin ga3",gangarea3,"GA3 Heroin Drug processor's license",2000],
["marijuana ga3",gangarea3,"GA3 Marijuana Drug processor's license",2000],
["air",university,localize "STRS_license_air",350],
["semiautomatic",Licenseflag2,"Pistol License",240],
["gunprobationpistol",moneh,"Probation pistol license",150],
["riflelicense",Licenseflag2,"Semi-Automatic Rifle license",300],
["engineer",university,localize "STRS_license_engineer",190],
["engineer",licensesBer,localize "STRS_license_engineer",190],
["probator",copbank,localize "STRS_license_probator",250],
["patrol_training",copbank,localize "STRS_license_coppatrol",500],
["response_training",copbank,localize "STRS_license_copresponse",1250],
["sobr_training",copbank,localize "STRS_license_copswat",10000],
["air_support_training",copbank,localize "STRS_license_copairsupport",5000],
["falseFighter",Tairshop,"False Fighter Jet Permit",10000],
["terror",terrorshop,"Terrorist training",120000],
["terror",weaponfactory,"Terrorist training",120000],
["terrorVeh",Tairshop,"Terrorist Vehicle Training",50000],
["Notforcivs",Nicht_DA,"Notforcivs",1],
["Notforcops",Nicht_DA,"NotforCops",1],
["bounty",genjobs,"Bountyhunter",150],
["probator",copcar2,localize "STRS_license_probator",250],
["patrol_training",copcar2,localize "STRS_license_coppatrol",500],
["PDF",copwe,"Police Base Defence Training",600],
["kaviar",Kaviafabrik,"Caviar license",2000],
["secAgent",govjobs,"Secret Agent (Approved Cops Only)",1800],
["secAgent",gunshop1,"Secret Agent (Approved Cops Only)",1800],
["doctor",genjobs,"Doctor",300],
["basebuilder",genjobs,"Base Builder",400],
["mechanic",genjobs,"Mechanic",200],
["basebuilder",copbank,"Base Builder",400],
["medp",copbank,"Medical Police Officer",500],
["armored",govjobs,"Armored Car License",900],
["hunting",university,"Hunting License",300],
["hunting",licensesBer,"Hunting License",300],
["iedmaker",bombshopowner,"IED Maker",50000],
["TV",moneh,"Donator License",1],
["vehicleInsur",insuranceMan,"Vehicle Insurance",1000],
["vehicleInsur",copbank,"Vehicle Insurance",1000],
["DJ Training",DJguy,"DJ Training",120],
["Life Insurance",lifeins,"Life Insurance",250]
];
INV_LizenzOwner = [];
